Update release-binary script from tezos-packaging
serokell/scratch pull request #11
Opened 2020-04-19 12:58 UTC by balsoft

Update `release-binary` script so that it uploads all the artifacts separately.

2020-04-20 12:15 UTC, gromakovsky commented on scripts/release-binary.sh
> -# 3. When you think it's time to make a real release, edit the auto release: change the tag, write a description, remove "pre-release" checkmark.
Why did you remove the instructions btw?

2020-04-22 11:00 UTC, zhenyavinogradov requested changes

2020-04-22 11:00 UTC, zhenyavinogradov commented on scripts/release-binary.sh
> +#!nix-shell -p gitAndTools.hub git rename -i bash
I think `rename` is not used

2020-04-22 11:00 UTC, zhenyavinogradov commented on scripts/release-binary.sh
> +nix-build . -A release -o "$TEMPDIR"/"$project" --arg timestamp "$(date +\"%Y%m%d%H%M\")"
Usage instructions above mention `release/default.nix`, but here `default.nix` is used

2020-04-22 11:00 UTC, zhenyavinogradov commented on scripts/release-binary.sh
> +    assets+=("-a" $file)
`"$file"` should be quoted

2020-04-23 05:10 UTC, zhenyavinogradov requested changes

2020-04-23 05:10 UTC, zhenyavinogradov commented on scripts/release-binary.sh
> +# Build release.nix
```suggestion
# Build release/default.nix
```

2020-04-23 09:02 UTC, zhenyavinogradov approved these changes

2020-04-23 09:23 UTC, merged